# Generated by Django 6.0.5 on 2026-05-27 05:32

import certificates.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('verification_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('certificate_file', models.FileField(blank=True, upload_to=certificates.models.certificate_upload_path)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', '-issued_at'], name='certificate_user_id_488ebb_idx'), models.Index(fields=['course', '-issued_at'], name='certificate_course__6e6bcd_idx'), models.Index(fields=['verification_code', 'is_revoked'], name='certificate_verific_27fd6a_idx')],
            },
        ),
    ]
