# Generated by Django 6.0.5 on 2026-05-27 05:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_views', models.PositiveIntegerField(db_index=True, default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('average_watch_seconds', models.PositiveIntegerField(default=0)),
                ('active_sessions', models.PositiveIntegerField(db_index=True, default=0)),
                ('engagement_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('last_viewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'course analytics',
                'ordering': ['-engagement_score'],
                'indexes': [models.Index(fields=['total_views'], name='dashboard_c_total_v_3d7ade_idx'), models.Index(fields=['engagement_score'], name='dashboard_c_engagem_d40df3_idx'), models.Index(fields=['last_viewed_at'], name='dashboard_c_last_vi_77fec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('course_view', 'Course view'), ('lesson_watch', 'Lesson watch'), ('quiz_attempt', 'Quiz attempt'), ('purchase', 'Purchase')], db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', '-occurred_at'], name='dashboard_u_user_id_03cb95_idx'), models.Index(fields=['course', 'activity_type'], name='dashboard_u_course__5a0a57_idx'), models.Index(fields=['session_key'], name='dashboard_u_session_f0cd4b_idx')],
            },
        ),
    ]
