# Generated by Django 6.0.5 on 2026-05-27 05:32

import accounts.managers
import accounts.models
import accounts.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], db_index=True, default='student', max_length=20)),
                ('profile_image', models.ImageField(blank=True, upload_to=accounts.models.user_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, validators=[accounts.validators.validate_social_links])),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list, validators=[accounts.validators.validate_skill_list])),
                ('experience', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, db_index=True, max_length=80)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'verification_status'], name='accounts_us_role_812b02_idx'), models.Index(fields=['is_active', 'is_email_verified'], name='accounts_us_is_acti_cfc41a_idx'), models.Index(fields=['country', 'city'], name='accounts_us_country_fa4d73_idx'), models.Index(fields=['last_seen'], name='accounts_us_last_se_548692_idx')],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
